services:
  - type: static
    name: calmconnect
    env: static
    staticPublishPath: .
    buildCommand: |
      echo "window.OPENAI_API_KEY='${OPENAI_API_KEY}';" > env.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /login
        destination: /login.html
      - type: rewrite
        source: /
        destination: /index.html
